var ALL_PATHFINDER_LANGUAGES = [
    "Aboleth",
    "Abyssal",
    "Aklo",
    "Aquan",
    "Auran",
    "Boggard",
    "Celestial",
    "Common",
    "Cyclops",
    "Dark Folk",
    "Draconic",
    "Drow Sign Language",
    "Druidic",
    "Dwarven",
    "D’ziriak",
    "Elven",
    "Giant",
    "Gnoll",
    "Gnome",
    "Goblin",
    "Grippli",
    "Halfling",
    "Ignan",
    "Infernal",
    "Necril",
    "Orc",
    "Protean",
    "Sphinx",
    "Sylvan",
    "Tengu",
    "Terran",
    "Treant",
    "Undercommon",
    "Vegepygmy"
];
Object.freeze(ALL_PATHFINDER_LANGUAGES);