<h2 id="Magic-Items">Magic Items</h2>
<table class="table table-striped table-bordered block">
    <tr>
        <th>Weapon Abilities</th>
        <th>Bonus</th>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=JIWwDgpgTgbglgewK4GcBQBxANgQxNCAEzQEEssBPOAOwHM0AhHaiRiFmBLdgFzQGEc5IgITVCSAMY84MVvwRQoCFLPnJqPaDXoKkUHLQjJ0-KEghYBSatR1oAIhByFKjiADN2hew7gpIcnsAMVwQEOUUPmD9RFRMAAsVHgACHmRJBMwDCg8w1gxlGx86TCQcKB9mNAAJZygeFAgIAGtoWptGkGqAKViotABpZuohuBSPBEl4gBk4EDtSgFl2HEl7Fah1jyQrJbhaBJ4KFMluHHhl%2BYgZSTQAOQgkHgMsOAAvewB5cOoTNAACrhqBU0ABFCzUTL2ADKzgARooWGgYUlJC0UYEsCkoop7AAVBI4ADuBISylJpUJxW0pQAakI4Mw%2BHS4OsTEA">
            Melee
        </a></td>
        <td>+1</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIEwbghgdgxgllA5gKGFCAnGALONWzYD2GCKwAHnEQLYQAueyAwiRkQM5xgCmABACMArhg71kAER4AzONHES4HAA48ANmrKCRYyUoxDljIlGQAxNRBpbho8WZEBPASVMBxNSWpCOyABJEao7IAJIwjtp2oYhQcIxIoTTKEDDiIVBgcIgkDGTIANJwfAj0PFBc0o55ADJw0jwcIog8yAByPIi5CQAK2BAc-J4wANZ5AMrEIzY64mP0EGqjCQCqUMRByADqREJQIGRAA">
            Melee
        </a></td>
        <td>+2</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=HIVwNmCWBmCekDsDmAoASgUwA4HsDOkALpDgoqgMpYYYAmKVGEABHoRgIZTJA">
            Melee
        </a></td>
        <td>+3</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=EIJwlgNhYIYHYBcAEBTOKQHMCeAoAIvAMZhya4BqA9iAA4wS4AqI8AzgGY0C2MCYANxQEArimhkgA">
            Melee
        </a></td>
        <td>+4 or +5</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIEwhgDgLglgbgUwFAEkC2EECc4wPYCuAzkgOIA2Ya2CISw55AnjAHYDmSAQmK8gMJhGtJPzysQBAMaxEo8UWy4O8rFjxF4ArAQTlRBVqzacAIjCJReU5ADFKaE0lvrLSABKGoRNLyQApAiwLKCQAGRg0YxUw6QBrJiQAWWwpGAAzAn0ABUpWMCwkACU9GDAAI3JkEqgg6M4AZQQEOKcGgAs8KTikABV2wxBsEyA">
            Ranged
        </a></td>
        <td>+1</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIOwhgTgxgFgllAUKWB7CcQHNkA86oC2YALgogMLoSoDOcAbgKYAEARgK4S0mIAiTelnBlsAGhYAbQbSYREAURAATabVoswhQhxBwyqEIgBikrZizsuPRAAlUkgJ6IAklEdXuvF8P0XEAAowYLJSqFAA1v4AyjDhUdieNtEkYJIJOACqIHFOQA">
            Ranged
        </a></td>
        <td>+2</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=DIVwxg1gngNABAcwE4FMCGAXFSBQAlFAGwEs0AjQleZdLXAZQAcUUATHAISWMJLQDsMcFP2wIoOACIoAzsQT9MxfgmqpM2HADliAWwoo4MgBYB7DDnoowp-qzhhjAsCiA">
            Ranged
        </a></td>
        <td>+3 or +4</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=CIJwngBANg9ghgEwFACE4DsCmSDCN0ICuAxgC4CWAbtniCDAM5U0iGZS6HrrnoDmSAGJQ4AW14DB9BqSQBxABaNSEUjBIKkAGXKie-JAFlMIYuQBmhDgAUR6OCCQBlTJgDWE50uJukAFQUuBBMJIA">
            Ammunition
        </a></td>
        <td>+1</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIOwhgTgxgFgllAUMAHnA9gWzAFwYgYXQgnQGc4A3AUwAIAjAVwjJ0QBFqKBzcPEbgBpaAGy5lqERADERYTHAENmrRAAl0IgJ6IAklC3KWbXbzj9uiAAowwE0eigBrRZYDKMRy6VNjiAKogntpAA">
            Ammunition
        </a></td>
        <td>+2</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=EIJwlgNhYIYHYBcAEBTOKQHMCeAoAIigM5iZwwJhyYA0SmIKFGQA">
            Ammunition
        </a></td>
        <td>+4</td>
    </tr>
</table>
<table class="table table-striped table-bordered block">
    <tr>
        <th>Armor & Shield Abilities</th>
        <th>Bonus</th>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=EIUwdiBuD2A24BcBQAFaBLAztMBaATiJlggIZjLCmzkDGIAJksOggiPs3Ju-umAHNm%2BUgHdY-IQGEAFqQC2AB3Q4kAEVI9S%2BJmpCkEM%2BJkzqQAM3TlkAMWj4E6S7QMqwACgkCZCAJRIAcT4wBkkkAEklDkgVAFdTAFl0fHx7RiQAZUUQWFgAAh57MIyyMFoZMIB1bVDBIA">
            Armor
        </a></td>
        <td>+1</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=OIGwhgtgpgTlAmAoAUgewK4GcAuBLAdgOaIDKAFmPKgO6ki4DGA1ogKIAeADgrnhpogDCcKJwLEASmBAgAnuNLcZAAjiZcOMPgZQAFAEYAzAEogA">
            Armor
        </a></td>
        <td>+2</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIEwFgpgzglgbhAUACQPZQC4QDYwHYDmiASgIYgyl4aIAiOc%2BRACgK4YBOMIiAYqhwwwAZjADGpIajwAKALaoQEDpIgBKRAHEw6DAAIMqVmLCIAknjitseZaQBGMXBgCeiAMoAHHNj0doMJhUYhAyAIwArBoAKjAYVOKIAOpOIEA">
            Armor
        </a></td>
        <td>+3</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=BIQwTgtg9gdglgLzjA5gKAMoAsQBMoDuANAARwQAOYUAbgKa6YA2cAxgNanlW0NoCiMOmBQBPEmDoBnOFIAuIGKzpoAsuDmiwydBgp0mTCdNkKldABQBGAOwBKIA">
            Armor
        </a></td>
        <td>+4</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=EoSw5gFgLgpg9gVwM4CgCqA7ARojATdDAJ3GnmRQDVwQAbAQwyhQBEZYiBbEDeqEOBhQBlCPTxwA7gBoABGCIw%2BMIiNogAxgGs5CpRxQBRDCrABPWYqQgkURhphyQnAA5E4ANxgFDUCCqVaEyRUTDwlPFkNQSh3WnUMMCMTInNLGGtbe0d5RWVVADE4In4AM00%2BAQwACn96DzMAShEXGHj0zLsMB2qARgBORqA">
            Armor
        </a></td>
        <td>+5</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=AoewlgziB2C0BOBTCkAuBDaqBQBBe8IA7gAQDG6qZAFmNAObYBC6EtDzANnQCZ2MBhTpnohCAVwjYAIogBmYTDgBiY1GAUV1MABTd61VAEpsAcXi9%2B2AJIBbAA6J4ANzAhJ2ALJgCYxD2wAJXRbW34gA">
            Shield
        </a></td>
        <td>+1</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=EoQwNmCeCWB2DmAoA6pATgWwM4CM0FMQAXAC0QEFZoNj8ATCtNAewHcACO-AMzHwGMi0ZrEQBZfGnhwkAZQAO%2BCOwJZoWIiFj98ACgCMAZgCUQA">
            Shield
        </a></td>
        <td>+2</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=BIewzgLgpgNglgOwOYCgBKBDAJnDCIoBiIAThHAGZwDGG5ICAFALYhZQl1QCUKA4gAtwEAAQQQAV2oCUAZQAOsGCJJQwcSHmpRGARgCsvAOpwYWIA">
            Shield
        </a></td>
        <td>+3</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=KIOwpgTg5gngBBMBnAlkgLgQxAYzAKAGUAHMAGzIWTS1zAAoBGAdgEog">
            Shield
        </a></td>
        <td>+4</td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=CIUwLiBOC2CWB2BDMsD28BQBReUDmAngASQgDOsZYi8AxiADRGzQAOkqAbiACYYCq8HiEQ8itdGA4AbaQjzZckQiXKVqdRkTylkUDADFUkFADNYtZGngAKABYjOBAJQYASiFPSQtFPAUAyqwgsqoUVDT0NgCMAJzOQA">
            Shield
        </a></td>
        <td>+5</td>
    </tr>
</table>
<table class="table table-striped table-bordered block">
    <tr>
        <th>Armor</th>
        <th>Shields</th>
        <th>Weapons</th>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=LISwLgFgTghgNgAgM4RFMAoYMlgKZQDuA9lANYIxQC2pCdAdsQwLTUwDmIAxvJTXXYATPAkLgIyAA55uIPu3xR5cIA">
            Lesser Minor
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=DISwbiB2DmAEDOAXApsgNrAFsghmAngpiOgCYBQAIjgE4DWA7gPZOmwBCArgMZ1rI0qtRizbxiZcgFkQiTDRwZseQuJJpSQA">
            Lesser Minor
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=CoJwhgxgpiAEBGBXANsqAXAUAZTVADrGCCAPYDumAIogM7pIj0IppbBgB2A5mgqcizYIIKGAC2ASx79BmALJh6McqRABrWLUnIAbjFgATMN24xMAQWQQAFlCn0A5LRaoMmAMIDDsSWU6w4kroKmqayKQ8tKoghpgAEnQ20txEJBQJSSlpZOQANLDcomAhIJgAUmD6yNKwpABmsDXcNuicKThiINnEuTiSAF4DNTK9GQBCiOnk2Uhu6AVotLTmNMzwAkLIYACePdNAA">
            Lesser Minor
        </a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=LISwzgLgtghiA2AoA8hAngVwOYAsAEOIAJgKaIAiATjFgPYB2hpeADvDBCUA">
            Greater Minor
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=FoewtgRglgpgBAZwNZQHaIBawDYBMBQAwgIYIAuMATgOQKY4EBCArpQObbE10sDGS2KvgCyUMhkrFscDDGIA3AJ70YeIA">
            Greater Minor
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=IIEwhgtmB2AuCW0CmACcBzdSBOAoUkMCyKARmLLADZJgAeSuAQgK7bYD2A7oumS1RqwANCnTZasHLgDKVMAE9eKMO26jxk6QBkYAY1QcAZigBWHFgGdi6WQAsKU7JYAO8ANZIgA">
            Greater Minor
        </a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=KIGwbgpgdgBAxgCwIYEsoCgBKC0HsY4AmE6AsrgE4i5wDWBKxQA">
            Lesser Medium
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=MoBwlgdgpgJgBAZwBZigGxgKACICcCGA5gPYQJr4CeUuA5AoiulgMLFoUgJgBGaUcAC7EA7jUwAZMKXqNUGIA">
            Lesser Medium
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=EIGw9mAmIKYC5wJYDsDmACA1gV0wJ0QChgxsRIY8ALGAQ0nQFtaBjGYugZzm4MxnQsQ2AEaEAYolRU4lAOSd0AMzB5MhAKIA3SkvAB3FBlqcADpVSIQwxoQAS2PARa1kAgI7ZaeWXm60lJUIAEVpUVEp0MCV0HWQwWwBxcAT0ERB6dgAVAgpkOCiY-xErRDgAT0IcxDyC6PR9b2QjQgBBTk4TThQFdEgwiLwQgcj6yFJ0lo1vOBpkPVorQgBlQyU6kW7IRFd0VDw6OFoAD3YABTAMggr0KlpGRkpiDIpCtJRttBWqRHX5RU4qjwYH0QA">
            Lesser Medium
        </a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIEwhgtmB2AuCW0CmACARgJyWAzrADgDZixIBQAygPZWwAWOYAnkhgOQ4oZjwRJxkAogEcArkjwZ4MFERLlB0AMZ0YpECiRJCOANaIyAISrJCEzmZJ1WZALKiMIVqw7piS3UsK06ZAGJUhCCIAOayxKRGWLgEEahUAGYoAG4w8Dh0oUA">
            Greater Medium
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=MIQwzgLgpgTg5GABGAFgSygGwCYBpEDmMUI0MAUMFlJGiJsultuQLIhaQwD2AtoxhzkAat0wBjEADs04gc3IAVKLwAONCPJxA">
            Greater Medium
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=CIJwhg5g9gdgxmALnAFgAggVwJYGcwgC2ApgFAAqxMAtCNjBGrgO5QgAmFdisA5LmkR12VRKQCyYOMTRQAZk0LZE9CABo0AG2K5cxEKWB4CShmgBGmsCNIAZMLnTzBKGSijNtBgMopsxTXZcAAdNZUR9LTB4MnJhUVkFOTx0OChCQmjOAEVMAgiQXEQwOQVnADcwTE0VBlIAMWwQYnZwAGsZYLweTVIAJWw01GJENBQwDP0GqxJBWCwyb2CCNuYwDqZikDaYbDkyW0w4NosrETQACgAGNGYUnQBKUm9WDkSmTHNEbUQAT2fXux3ohXGhQtEdEA">
            Greater Medium
        </a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIJwtg9iAEEGbQJYDsDOBXANgF1QKABEB3AQxADcBTZaAB0xO0rwCETkATSj6MExTLASZ0AYwDWeAMKNU4lNEyVGAC0ohplJamyISgspA0sxo9pXUByVNABGIZTvqNmABQZNohqEOjY10FyUtEA">
            Lesser Major
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=EIQwLmA2CmC20DswAIDOALAltSATAUAOqYIDm0uaWOBAggG4iQgIDG60V2e%2BAYgPYAnMIOipUXGkQCeg2KmbToggOQSM3XEA">
            Lesser Major
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=HISwdgpgBANiBuEDOUkBcIEMYQE4CgBVMAEzwGMBXNNcAcykwA8J8BlABxFxDSnOw4CAEQDumXADMARgHtSUABaYAtirz4A8pjSK5o9qNm4SUWZNghJ0dFjhg6%2BAMLVduWToDkKTBw64IMFpyCCA">
            Lesser Major
        </a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=EIJwpghgzgLgDgGwjMACA9gM1QY3QW3wgDsATAKADF0QoIBrMY1AIxNLFNSIEsFyAsjxgALEBASpMAVwSTEyNFlRQ4YTuQDqEEB2bLRaAO7p0pKOQDKOHRBatw0eEhTkA4jxIwAtCJ4dUHXwaVAAKdABzcABKcgAJCCIYWQhUPw53T2IfdLQgkNC-OVQIrJhYgBEwYOZ8kEyvX388kGCQUNh0YjAAGikecD6QzBB0WBKy2I9G3MDWgphRuViBCD4MbCIEMAA3dG3iHDAG7KaAutCcBHRpLlKvKbKzlraOmBp8CYfyCogAT1gOjSEkw3gUrgAksQdjxDjwWNs5m1yAAFEA8KBJHg4VDgsBAA">
            Greater Major
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=MoBwpgNhAEDuCGAnAJtALge1mR0DOAFgJaTIBQAigK5EDGA1tAEYQYPNUMQ5kBCkEIgHMcYAHZp8xUmQBiGRLTDosPAIJM8CpkTFCpJCOQCiEAJ54i8MQdJA">
            Greater Major
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=OICw9grgNg5AzgAigQwLYFMB2AXAUAWWQGN0EwAzBbdAJxrBtwAl0oo4jIaBzdXAERrJuYTPAQATMGFS4AMgEty6ALQSaCzAGtauAGrIoDcak0LRuAMoRUqUbXFwG9AO5WAnlABuyTAg4KptjIjJYADgoa2AgARigSfCwh2HAu0hL%2BYeghuABKyBG0ZJRhEJhE2BAamNxWZbHxfABCjcVUIKQacJrc-mW4AGL0cNExQpgSAi4hXljtrrot6dggkSOSwryMAOohYz26chBEWg3ICQgAFACMCC4KcCAAlLjAECESPWcJuAAKD9gwFA2itSJpyGZqP4tO4CMRSBR-EEergWucEZRQf40jQJCo4MhNHhLERAgpgjQQR1MqwoCsFOhyFYIgkaOJyL5avx0HZME46GAXAgiFVZt8%2BHowAoMhx3KD5MdTnF0VcAEx3B4dOAvJhA9wIZCzGqLZAjD6ObAoo4ncVXADMGse6G1QA">
            Greater Major
        </a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIEwhgtmB2AuCW0CmACAQgJyWAzrADgDZixIBQoAbgPYDGJSA5DisBhNRhYbQBZIR4eZigDKAV3ixuhALSikSRAHNW7ThQwAjTtkJqOXNoOVIMI4xssYU1AGYoAYhjDKISOCrGxqyTYdsHAEloHHFCWBx-TkCUWH4xGBAo61j41ABVaABHcQ8%2BMC1CVEd4LDI0MFoAay0sMGqzFABZMHhCCqSkEBa2-XsUABlxGoriGrsVMxZgfAxfCt8kYpwWQex0rkxsPCIGWIBhaggoaBAK%2Bt3iUliANRghXhUKkfpkMxFt3AJr8gOSHDVRBDDb8LgHZZIPDwMD6axkCErBCwlAABV%2BBg0B14bWgKFuUNgsQAImAAO7QBEuVSDRDQTgQNG-MikgCeeDANgAErC7LJ0QwWaCRKisDgzJQSPBfOguj1Wu0hRw8fDidTfHYGZiuGrXL4niBUALSCyyZzKB4mYKAKKEC147G4sjWiD4Vn1OHqLjW6AFODdFDW5aAxDO3KEjAwvHG8jW0gYaAooLzPFfK6CxwwZQIQ1iejFXqK0rLeXdeC0T6XH4Z4g4XjKcScnoxsiOaiEEBeFttjCmKB4D4sHmEPndzg4BqWypnAMKjqOcL6GNpBJHDD4cVkADiy3Eyhl8J3hD3MpbW941HCKC58EN26jsFkN9zh8I1GOhY6W%2Boq0gTVEvDzOIyQrqgBzEGUNCsjA0hbi4FpmrAfBNI6iBQIqcFgKyvQDuYaygtMZDDqOGIDOkKCkhg1RopGvrkDyUCwOEYDXre9HLIQZo4PgKBruK0hcmY1AiDy4haGY1REeI-p4SCJBgmQISTBELg%2BLJc6KdAYJSJwlY7NWJohJQiC0PARSoPCABSwGmHp3x7Ca1nQMoBbwrSdhILQ7bEDYRwkGQww1J%2BAA0KBwRsZgBSM1FzqF6yrJFc6xK0xQ0MUdFkK0JzUPErG5gAFEEogHAAlJlkAcLlz6oPlzQACp1WVrR4s0l5wLi2qZUIsDoR0zRSIBKILoQS6kQ4oj4Io5z9fELj6ABZTSK1GBvkF1WZT%2BOCIf%2BsC4gG6zyYl4gYIaWCyWg4zVLQb7xGQADysCsnuvB5eQqK4tx8CNJ170jbevE4qGqLLESZEJMSAgyq1mxkMDGAebQCAygdMOoheHjwAAHj9GKpGDqAQ0g%2BCw5GOCMeWVomgASgGoi7YQjQ2PCVNPPSr1kFTP7YaJ4lUWQoj0C4WjoFWDnkALl4IM5ckwwoLHTnWii8dQ-ly8rqvVIuIDiLh-PVNhADS0DwMovBEmqUIsFk8Cauw-OJu0Yv25OOD5hZXr8%2B%2B8QTqyg4oFTbTuHA-P00C0vwnTnJ2JyXic%2BJUSRxgOC%2BKoGl1SbfvrenWArCwdUuDUXhZ9Q7R%2B-CdXScg%2BgQx5M42HTSxOwSpc9KhlIAOqcsrJxdLJxYdpT5Cdydlr4yg7fvskZCdxakanSL%2BlO%2B38AAF5NiIGkT1RpwWB77eRvEXjwgAGu0%2Bj-C4%2BBVO7hhAA">
            All Piazo
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=IIIwzg9gTiCWB2BzABAZQBawKYBsAmAUMAG4CGOp8AxulmproQEKkAurOWAtlvK-dnwEmuHLERYovfhkHMcECHgBmWUmBkMhTKBFJ4wsPHSYBXHAHdSUANbDd8AF50A6pjAAHSZIDkYAYzCplCIFFB%2ByGZUNpxQBADC6qy%2B-rKB8bhYGrDkAULxEDgUHoYgnMgAKhAWkgQAItY2Fop4kabRsfWNzUp5hHVQpIgQ8GAUAJ4pffVQsMqsPa1pQgCinB7olJpyBGvjhpTTKwCOpuSwzlDTAGLQVHRVNXG3UKxSYKlahADiZ1CtEGUyAAspQCAAJapiJBoGzmHDIYBQLjQAgAGVgIwiy0IGJGAFpUHCisgANJhdGwYgIFCoZK4ZDgtTEcbTUG4DS6Lhs2CsdCDBFM0gs6YARVMsGikQUUqiMVqOOQgOQBWI3laACUsG81KwCIrleChmB9V8lUDUKZ4LMwFhTXJzcg%2BXRQc4QNB4PqKGrwv5QXhTPqvCSXNZWo9JNNUMGcCBKHQcUGEFgll8k7NtoEKtwvBppgA1QpUSiS6YuGkpsvjZFjUiTX3TABaEC4cATNgQfSAA">
            All Piazo
        </a></td>
        <td><a href="/tools/tr/tableroller.php?t=IIGwxgFgpgtglgZwC4HIEAIBCBXEIpIBQwATgIaQB2cAJmugGJmUDmxJJA9gO7qcBm6AMIQyJeK3ZdeAZQAOIOEiRQSxBAjIa4lephBkaUdZu26MAETIsWq4gDcyBypCjoZi1u6Rl%2B-YgAebgKMUHg6bMBBfIIMnCRgUDToADJw-MaYWj4kdBgySBGEWcr4ZEEANOjANGQwzIWUmVDZ6ADqJFDI%2BCT0AOJk2JRI%2BEgIxS3IyCRwANZuQiDYAEbFBkYxWDo0RfqGwYJI0OgASogR7kNr%2B5tHbjLc8TQAtDJkOkT6nGRjSDPz6AAKu8QGtOJwaKNGix0ABpbCzGZgiHIThNdAASRgcicdi%2BEKOcBIyHQVhseJA4JogEwCDAAURotmK31yFwACnMDqcoHIwp42JhOLgjCQsLhRszhapoIZ0ABZCiZHibYAIaDjTAzJr0Aq7bAcHgXHB4AiEIRkRwgEgAT3q5iwPDNokoTR69FVvJILDgeGwMDNaOmcDASHi-UGw1G4yEMxgCDRWCWfjN2GUEC4P3dcjknWGweMZNsopCFiFy35hELqk2ADUoJROP6qyQqjU6g0dAXmGALm0tHJKy0aPx8Gr2mJygWoGBZpsPHB7KoLkwVIOYIH4tJhPrF4n9oP7D76LCoNbK4gxBIYXsjOeAF5361G8Wm0vZsIsZhFnWPXKV8gsGi9Clo2-7WEBGDAj6YGAZQ5ZQEkdgWABaJgD8kDoH02AXuIBbYGE8rZKo9AMkyFj4YoyD0EIjY-HhJKCiARDkcgyz6gxL7MdwYiCDI9Rqkh3EkPwyxoskAASdQwIJYiLpQQLpjwgnbPyYomkQdLWPgejrMYmkkEcWCdGQ8zFoIZwsBAKjJBilAAFbYMg%2BaEPpdyUCOIIuX48QjF0GApIqLmLsJlLcBcHqqN6vr%2BkwrBJIwTiQHAaKEAwcCWSovQYHEJCzKlOhOO0Tz5Z0NDkACHKoqCDAGNJQJoiw%2BGpaOEBCbyyQyGA8RyMl9pQdVXAMeQlA0Klg1IMsSj3BWDBcHe9bCINCCidwhB9BAQogPQAXScMa0GAuUDPFhOF1SEgLHDWX7YGIo19JSjZ7refTkAgPVeIxWhrZ09bllS7hdfqTIvdgjJuDexhYbdRq6YQ4lDggdo6fu8NiH8cDvqKENwy0BkII8ELuLyYg43gaEmll6CkcY8N4AggNejTqicLST005wIDWtUclFnD8QIF0G1dHOFCle4PrBXDQyZTqOSzNQGRSxwwbMG4ACKN0GaoyC%2BP44mORA4UGqtWI4j0mwXfElDjBiHCGHAPwXP1hAAFIWmEOibGkGXUJILug8GDsgOgkkwNJaiwtQGXPOacg%2BDo23dsYsLWqG8mdUKjOEAFiTkNCpxkD1dgBTQ1o6j15CggFLhci7QpOZIAVjiEdwhzwPTZ1ALDLMZpnZ%2BkR3ITofdpHet31Ll8XYykDX408VQ0SANlcPJCrIKov55Sk2AzmzhAKokc7wNC%2B%2BKhbqhcGoB-QComyLLjRQKrY1FLStp8uIbFOn8bYDkDOdhrxlhgNonB7iFChJwU%2BuBbjHEBEoZg4w5RomyMGccuR6z71TG4KwBlCAADk4AwHgu0Q2A4CHojSIufIKhcRqAAPImQWgUXWhAGFHDfnQyg1oAhE1xoQNkLREjzB5OyRAoZQRslEALaoxt%2BFiI5jAtwtl%2BA6Cmu4WYZ5KriKqDPUGapOBEDZBzMQSguah3DvwoGy5Eo-DIIQDWaNtY%2BD8HfNEKhsQGEKClBxWtiTOMECEK6uAT4nDIMsSaqAMDY1CUXMyWAfi%2BRUWEZISDFy7SIDEuA1YQhsiGCGfURQTgtGCqzTqqdoCECKSNC4iwyC8GiTyHyNS0YzDBpU4MnBXBIBDlJOwZwBbyWiQY8s%2B4ThDCgPwcaPSkBdMIG8X%2B6RA6FQeMVN4OwqL%2BS0BAOZPZj5iEUbwvAhIJk7KFPnc0BlWlMk6sZK8DomJzIfl4Ug0hHm-wIItTgGg34yFUIXQ2YB0BaI5nM0QGxBSrRkGCngokhjJBEO8a2oKEnax6vMZFygnFojcOYuwUKnkwhWX%2BKFWSl5vUUJi0U1dEigvSEA9wm5HRQs6bMbiu59BwtUGxDQoKZiLhACM28Mh0oK2ItlMRcyJbVmbFUQBG94h5WFQ%2BVSLymWzFwLMC4MhqCeh0jwRqlA5kaK4P-bpMYvnLSZQYYK1FVZzIME%2BZ5siPAITkDI15fFsA2DdPkCs2rGEROMP6%2BYgbSTWF5vIMQrLGHeCjaKuZPURT0FimweQRIlB7zTTMbpn1xhZozeaL%2B8gKX50YkQZhJAfly1FQcmsnBaBzJocOVoABVEgfo4CNqJLYMNuCZB%2BnXE0SmMhGWQqGJm7iao2Izh9QXWJcywr8G6XQ5YCBaAO3ki9FoPgggLqeF7Ae3gWh%2Bt-MkEI-bli%2BSQGeIlZ7BCAlgLyKYe7cgHLZM4LoL673oDrHFJOczrQgEcOnXZ8C1DAkpNbL29Y2DAnDvQNopDCDAlYPge5RAH2UGeFqGEc8-yYYoMlRy1QRg-GDjgjDG0SCDMdHAow3FMrblIzywEf9qzGglKxkEIz5rDpxLeLjSgwxRNhoJ0MXBiN7HXuB1p9ZukhDSmOGiYdmCjVY7QOTc4fCTQpWedTRhhgHIKPEGAwhC7x0NfpzTIQ%2BzUaKOphQR1dSsBhvudTad6BWb2i2kaqgwCpnzlEYwV1KSUzlKolKv7Gz1xIYgT0vaiA1m2MGQou5JIkDkOCQ1dbaAA3KcF3AQ6wk%2BlMehwgfZfOdGHWhYS5X9nUuMLZnuEQ7B9jeseRA4xENxaXF4KF-xGtwDHq%2B8S4JZhAA">
            All Piazo
        </a></td>
    </tr>
</table>
<table class="table table-striped table-bordered block">
    <tr>
        <th>Artifacts</th>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIOwhgLgFgpgtmABMATgYygSwG4wFDAAeMiA9gGaLQkAiA7mCtpgM5SIAypKAJi3gCEANmDQBrMMUGlSYspWqIaYOCBg9EACgDyKTAHNM4IQEpps%2BVVhKVangC4b8UiExpzcildq31jms6u7gKkEBBCJF6KIQCuIDyCKGAAXjAgiACi%2Bvp4AMIwESwQmGBCnGn8uVAoLm4RlooASgZQEDCkMZVCHRq5YEX1UdYAyhDccIgA0kY5uaQ8MIQN1gCSIORGmG2IAAoiavzKIGgziAASMRCWAmAARkgAmmD6YHgBcC67esckqB8oeAAYiI4JFKABxGKYHhgH5A7ieBTWQHcfShNrpbRqPDg%2BCWGgoGAqfgAKUY%2BKSaJAAHIWIgACowGDQPAAWVIsNONBKH3ieEasJ4pAmuluFOeLjERgSovFVMQrP6bRQAE88LKvASJSApSB1SgxZrKS42GAAA74HYwFDkGBoYouWlTGBq5ogfSWAByRhIgNEzP4jTiMDoBTKXnBhPUeGGYCMV1ylygt2tECdirQ%2BGGmbNysswH0MH4wygYCFdCKYHI5BjWAKGiGJGGcVrmHryxIAHUZupMiqs2IYkJw0iSAA1TAWlCIcHzGOD4csDpCGMuD1eDKEYrHB3pTSszpuRAhQhmYZ0bgNiFRhL06wCPTk4Rl-B3kgkkMFSwZXAoERFU5ZyEW8oG4Y4ajodIvGfAD3SAA">
            Major
        </a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIJw5gpgdgLghgGwAQDED2sBQAhCcDGGSaAZkgCogCuEqcAljABY4QLKlICyEI%2BAnjgy0AEmioBnCELQBrYmQCSUEvSiNaAZQAObBBJwg4UfEwVIAMvRLSAwiDQB3KOea1FDlwGk1YTPacXTjckTXoAWypwFgARCHx5ThE4EAdHCAATCkQIAziE8y5jfgomXzz4xLIiqBLyMqgwCQAaJGTUp0wYozAiTTwELp6%2BhDh%2BXkwAUSgIcJLOYHYkadn6XMxk8PDec3qqKAzeACM0BBgDMSiwUYkJc00mOAynA0UsgAU0EBgjRkwvKBUBIICAnGbmFD0YG0dDffbSIog1T4SShbT0WQI4wweh3bCjQ6YLgYTH8ADkd3ecEcmHevBs%2BBgSAA4qdDi4LFQYNJ3mUEGgJGhtExeBTQjBhLSmPxRozePMyCEUAwQRlMAAlOAAN2ggEwCO4iPBq9UQHWjHFEACKVHo7A18Ik%2BBSIEySG6cF6UAkZW09pmElGOqQtjgVAQGU8fog6SWwEiIJgUZjCFaXDUX0wOhFLvMwCg6j5cAtUEz6IOIPMdJADKZAKcqsgmfgJDIwRF3A99Ew5EQuPCxkrUVorLQap7CD7A84JoQQPgsCQAHVcSKDOPJ0FFe2s7xpOuJP3N0gAKpnCJF2iTLW2zDHmYHXwUNDbTAANV4UEQSC8EEEr9x9AYCkJQWNABiLikGSPtgaAAB6YIuED0CAWTWhA0BikUYDohAQA">
            Minor
        </a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=EIGwhgxg1gUKCuBTOAnMBndqD2A7AXsgMLYAOpiKMA4tiACY0qKK4wBKijAygJYgA3SjADqAC14AXZADFszdJJjdEYZVACey7EOa8A5mwCquepQDu8hql65iIbPEZEUGxWBAwAsmH0BbNSM-ACM0ECA">
            Orbs of Dragonkind
        </a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=CoCwpgBAxiCGBOsoBczwgc1gSwHYGcIBGCABzQFtZcxdkIatlsA3SAGzDfYDoAoUJBgIkqdNkL4ArgCMAVmBQRkAewiwyKgO5oAZlPbQVFUgfzYVuBlzTK18Fe0PJwEANa4pUN5xmXIKroQutjenMEq8MhSNOpYeDwQABJC1BD4cG6QLhJGJmYWVpbsAJ4QMmXSUFBgYAAmeBjqEAAiAMIQAEwArBAA6thO6bAsjcogDlqJKdBpsMioJvQ5kiNjLpMQxWWWNWS2dbAl-ILQcIgotrmwurqKqHXlZRrnFOnkQwAUULD4YhCcbjEbouACUJ1cwgu-1y0nk9zszVI2j0BjypnY5ksiIcQxckA8Xh8YD8sQ2tQgFEi2WwFDAhFpdIa8zApQgnwGQ3aXV6jBZ%2BHBEAAgniJhTAuN6ZBcZj1PBIFQ6pAtNgXM1ACgEvXIuFg7GQOys%2BPcnjCJP8AHJCA1pY5DJ8KHhaVI3kRwQJIedRFdCDJ2HglY9fhAVWrff6aPh8AB6JU3COET64NT4Na4JobbRu05Qr3oZCwLKEbp1IgABk0eGQhAlUEcj0OVAwkE%2B3J6EAAYpF6Cm2BF0HB2LpQepcI8qWxCPMIAOgvhyPU%2B5LrAAPeggFRSdCfDRVGqR-SGHvrCbaCB1FT0hgqeh81BL%2BV1LwLue1Opuzt51w0VddAAs043eB8AAGiXHNLnQaRbjQScIAAWk6fYdT1A11CGfA3EGQxqEDGRBlVMoYEUNx8AhIRPQgiBclIERSgALwXXRIi6EtEPXTcQPUQgQxAAD2DHSw-jQUCwGXGpSDXVJcCTeh5kWCTrC0YZRjTcZJkIVQtjYeBazpJcwGglB%2BA-Jdv3oHQwDcUCjXA-4wAdKtmnXeB4GwX1IHwOknGmDypGgoDmjg-9tV1fUtisFpsFIdhjCQZ5RwgABlVBQt4ojvFIvgAHlcBqUDH1c1SjTMv8AI46yPRESifiseU4JlZpzDTcJrQgBrXDgQg5CkP5KVgJUR0efMsiXfBFEsR55WkPVQKDbAgh649IAwFQVEeJiohiSBYDwv0wt0Bw3iNAAZIkz1ihJ3XIqr-niAhiFLctkUrasghCeUqIoCgYgI2aGQWpqmlIBxUBQQpgkOiBaDQDBjius4btsO6NNcGRoZCRyJReNAVAkN4XyGDbTNE%2BhOkeyk8CkVBMpM4qSdK9igNArRwENSroVsEBVVg-N4CbSSqMIXR2GoTDVJ45ovIpHRYGRXAKu2hYkDcc7LwAaiIOoADYKzoV6yHlKAJHBhtYCbfgcr2PBiZ-Tp-0ZzibIo-4atmXrdFgNBsEgd7mx%2BIT0EBVkoYARykXVES5whbNsIP2EFUBrl2gjBYBFRevmsDndsGUUdyKaDFku7g1VXijUJU1SQCN7QmJPtoliNGNuyVw7bKgLclrXL2CkAMyIRjnxAZL6tsRO4EEXOnbftwDMstyBran0mZ-KrPEfQV3-dkgFsAwEBkFwMY-D1dkt9jmxDDAMOI80qOB9zAEL4Tu%2BdvwsLchijOgid9e2ttPPCAFxPmbHAVgJblxNMSKuWwa6mnrqPJu1IlxtwdqnLuUAe59z4LTL89MADsZ4jicRZrQNeg9U5Gl5vzGB04wC6jGI2UIoEOp0NlHMOoDRmCWAjp0OoAAOacqpdZVkSInQgBk7hKA-unegmcf7kNzkuCuUD-A0JCHAjaDdtrF0QR9I0BDDglEnB9dBmD6jGWYkvBms9masxsJ%2Ba65DdyvmrFYHcqZ0wniUiAvAvUXgIAoAeKGhllhwHoOeS8M5CGNgCOgGiURsARwkQibEGgPaDGfCMMACtjREl8BaaO2c8wFkvEmaJZtYnpD8ncAKZTklGWwZY3B0926O3Zg-WAVNYrMB%2BE4Qilh3oUEnEMKArkekRy5iI%2BGJVmB6XkQ-a0nFITGEvDIZWENjBLljENVw2kyglSpPAQ%2Bqk5rf1cHCBQSgsZtXpJuQ2XCrAE14BAMRwTJGyMILeBccj2mUUURAvJZpYgSnUXXTRo8fFWF0ZAVwiyeBAA">
            Knucklebone of Fickle Fortune
        </a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=EIQwNiB2DGCmBcACAwgCygc1o8BLDkAtrJAC6K6QDOpUpYAngHSIAqq206ATiNKbG6JCAVxqIumbKQD2ORLwAmuaOEaJlAM02CS5PAWJkWASU2JSHCTz4ChmkLjBULc2zmjQZ3ZZAyuLK0hYAHccMHwiPQAaRCorDEdqeWDE0lwAN2wwWCywJgAoZBliUiQAEVgdEHJLbGCAD3JCGWo7RAYZEWFYWFq5RMpEVuzc2Hy2K0lefkFhMXIqSgwcgFp0SEVYRQ0q2BrA%2BtgmxFQZGidsFra572FWmkEXEi8RMl1FWLu6xAAjEiquHIuBcYHOpFM5ioIk8sCoVE0IjAsR%2B01sc0GyRIXQwqEQAA0AAoBGq0IY-RrkY4AB0EuBeozyhXKrQAVq0kABNLo4bjYXCEancEEjRQsdggiQgHxxSK4TT0lwCoUiqJkRCwIEcIS-BiHCiC4VUVpGRa0sBgYY6vXG4iIakyEKCRGW-7LFgAQQtiCw0pwmzi5ucvOwNGF1NpO003BK%2BoyKnShAokH9etUVFgLHKvDCkDkLT5Up8VEKAFERLwGDkkKsAIz2kjgUh61rhS1UEDxvyBGMhFwcGBVbyWcVWACy2zEIFWEQA1th4x2sMNzJZJaoZb9hX4XCAJBWM4EDq11D8AGI1OFFnZ3PdbIFpqAKWAtLKj7B1huQJstlNqOKdssPaOkqLgyHU3AhCC2C0twhBQHohTsNgF4CFQSAehkMi4DsUA2kCIg1LgradN0XAyOcsBfIOo7rtKOyNr8OQuKiNizEIsg4FhOEalkf4ppQNB0AhXRgZ4FZ8oOFBQnIWxLHynyIJo3xWA4W4qCuz54M2FAuG8vB5Ns-o7HyqxUNSbwsAAcuB0joMC5CKDIV55lS35MaGJR9KgQGcegEYkKY5CqCmJ42rI1JxF5a7dtGsb%2BbSkBAXcfJZNwh57tSIDiDI4ncJJcDvs%2BaUdpakphUpKmcGx7QhGcGh8mEqL0QA3MMEH2tKOnEIQ-zpcIIB6ugWQBCQigVnZoYEURrSFGeEDEOhiClkQD5-H0TokB0PJQLhoUiKQSxbNwLAABLgf6WDcLErL7GCYgMLEu0apAGR6tK2C-Ad8g6GEMirlYDrwrgHn3OkGQzd%2BlrKdwcAuDD%2BokIQD5FUja3-fqXSHThcwhQA5OQ-wvVsOxvOklojJpPxZdw6RXugLj-FtVAQJQWZ9IIyPBJjB1HXMvCbCUjBPQG2XQnalgHECOCkLQ0CzixUw1XMAAUdzUhAGAiPTcwRDoyZRXaISDQAlIgUExYgtaKAATAADBog0lgUZ4UWASAADKUVbdvRHb-sag0sH0lJDqUIdxnbd0ojiIoOY4JiRVZQwpqaUSkc-Ap8cfQNmw1N4zCTHRMqSuAxsMC4yhUBuJPmwODUgCEkCxG8c7YP%2B4Has8DRwNStRWAAUnCdiFAA4i%2BACQSCj0kUdCORKjYBjNsAKz2vScOabdTpgNwLZCCvDtYIQJZFy4NfJsoqhoebd0jpM2Db%2BMe%2B6W2PoyGAOwZuQFt4sfVCxH2FwdesA4Dm2HHiG2fsA4YGpCLHYPx-4hnAbTPEtZoFH0ikA1AhQTDKHAkga2AAWAA1PWEw7wLT4AZA3IYApiDKEvKeOQrFpTohOogbk0dBrDD7sRKG6g46NwTkkQoQ9HjcGnrPWsvt-YO3Tt8EI%2BZvDYCEX2JSMYkw-C2PLWi596KvzLk7DQIIa5GTqltNRzdECt1wPON%2BncniB17v3FCbsipZ0bruQsMg%2BGtHAIUAA0rABg8AJ4zyGHueC7IhDwQwBpJ0IAHSQCKnEhJ%2Bxkk%2BgFgIHYMdCZL25lOUGup9RonYkFOIIhFBbEgOoJJtJpRgW%2BhjPMFjCzkiVmw9ieN%2By7SCUlXEZREARJTD8DM3B4xgIxnuIhlgZxjGhvgVAI8H5KSWe0ep%2Bx%2BpY00q07U7cAzjKyKCGQDA1B6jJk4XYNQcGIFOkvIQ8R%2BRgQBqGEAdoZjYDVkIWclBFBm2elgTYcxsqlOVhwiU8N1m4yfETWg84-y7gkDIM4tM-jvWsF02qWp9Qe32MdeIuBIrVAhAUMcFFIBch2oWDA2SjLEPNiCDgp9IXXnWo0-UAoQDLmmfcB4shubH0ZZYfU9SYwqkvIgSAIheq3HMFBJ5Lh4iOkRT6HI7zFa6EoG1W0fQBRXmllsakCYkUtFbL-CgEdqQM35JsFQRFuwUhlX1TSCrmWIBVi6S0ABeSqFY2rxN%2BL8USiBfWWD5LANq6AwDmDDUotqABHQitM5i%2BpGCbd8h43VXhzmM957dFbe1pXQIyJSfgAE45k5DyIygAXgY8y4xLTPTyetGxGYdi-0iVK51crhCUAOleWASbwABCdbKoQfI4CZG2IUAASjILWCBEAAHluYY1IvYYUY0WIVmSNypI4hSIsAAOr1zXPokulcczWMphjVhMw7A9MQFZQkyANEh0UC4FWQo9i8CYhirwqLSBm0lLIWgFp3oREbDkyO8EtiVVSnMM4FwciQjBVi5DoK8zIuAwAxGq0dIY11faR0zokQNnSv45c3zkWEFEElZsXxJ3jHwMRMQVpjpmxCm26EvwLikEHWKVZ9kFKvwzNAPk5BLmWh%2BImZ5CgiXYARtLTiRMkPgHMTirYEMhLpG7FUHQ-B50iEoEgEw9Hti4CYXqMEGVvSJLACK56QpfGCGbJ6JUgpoM7BKUCFw35iCxAsaMnyl6diSisU9b0eZICrDSaoS0QMMzAweFTKwaiQWFjs6SgAyrOJEYAp6IEqCShq%2BLza8BxXcImMMxhCDkqQGMDBZ2IA9OVkAnaqvOYCo0oqZT2itoVIMy14RKarGku1LupxxhwI611xwlhdy9Y4nIYbyzDhJlBTvCYZgMOPrmJKFmSRYhPPE6zFMdW0qRxCq5NtqUZ2KTGCmC1e43VWnkMjGYaGCi5doJIxAFmGHWYEOoTE8gSE22TPs9UwbpUsTcLKPwOQcC-CcGtauKj9vsOsBRFLhRctvCkUMf4wQFTQGs5aYHMrwGbBjBxoEL5I6HwwQSQkLAF3egRlEqzNOlF05DYzpMMn5BiCqBRoXr8-n2pyUhcADwMLegS5al8LhSKkfhHCSuIJNl%2BlgvBYIZBGCnvPWFtlkWb2ALSnqZXkuVVGXVucFLHb0XY-YlLtodA6kBlwPlXIuUQAAcQDlwBPdYB90Q-qHRs4kKoBjMEYnf5EAkIAGx-FaBx1s5QiVgngtANMHB5YuA1hxvcVB4LenTPQTMqyBtzH%2BF4Ra8gmva2D-iw7KZaS%2BJyM%2BkJcJ%2BvZWrz6JIRldf9UiZAFsiUQxl6sNm79X1XG7Ap0sc1%2ByAgaz4PyZoCw23wewF2lM9YzgVgzQUAAargWt9IAeBNaaK6gTpVtzylccRylx6MgD0Wyl8Don%2BasxQOwaxzCAmlgtR%2BBGFWHk1R3Rx0k4kS0tBEEyTLy6FhiXnlRBCci0TkGNDABGjwiRxWBghjA8iTFvEfzmC9Xekn0QCTWHn4RsUyW1GfDoJoCKjoJfhSmHW1nEFbSJn32FR8iPw6C2RN28jmB%2BEoBhngnSFbExCMh4yJmhFhHhCoI8FgyQNbFLlcmYJkPaD0F93GGYAKGQkQHP2wkUCQGABkEUD1ERBgFkOoFiEXyiglxYl4ACgYmcFCH2W-yYj4FnDZUbQtCVE93VCrkH0EH63BWfWDVsORTIAHSvE4nsP4H4SekLREFxDo3zgzGcO%2BmYOpCoAYC4AUya02QiyTxVGNBTF1TaVtX9GGF%2BFun4GGCTwcCEE33XU6IgGCFIFiGSxBnUA6Rgidy1wYOmX2mxmOk9EZXiA%2ByiV9z4BRychcgunUkdU6SAL%2BACNiEEgEE6x6D5HUA0wiE2Jgl6PQJenKOpFNCzHjhwwLE4HohLCAA">
            Deck of Many Things
        </a></td>
    </tr>
</table>
<table class="table table-striped table-bordered block">
    <tr>
        <th>Misc</th>
        <th>Source</th>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIAgLglgdgniBGAnAhgZ1SAxgGwPaYGsB3XRArZMACwFMATFbcKykAB22Rg1IHNkoIALYBXVBEwgitQSRFQ6AKFDxkvELgBmGqDQC0VeQ3rDkieNhqoANCCjQaYGHvu6QZmlKoQwngXWZPXGoaRBAIDAtkQmUQRHwAcgxNGkpaRFjUXGw6CFCQOmymLXdBGiE2CERPPChePU0%2BYN8oTKFkbCYhGkwWe0wOkFQoZDZKuvARRDBLWMqeoO0wUkFqgJxgqgRUxGh1ZDjcGEHocV57ZDnq1FCANxMaGBpVTvcwMGjaAOX3IfG6bBwR76VAfbAEWwhOx3KzgIg%2BXoaTADcS4EadGCxEi4Og0QRsEQAL0JlgQuAAHsxWDBcCIQCx7nZgkNsvclKBUFREPICHj6al2XEBFkhEzfCBGmEDrV6nhQXEaJxIIySjSpqhlIIqLTELxOOgJRBOiZ4dQQHrcPCJqh-FSwBKOtgMKg8ER8qQHaD8tQBOF7ZzaTlNRp4OJcr6JGiNNoDpLeM0%2BbifJjQNVMKRcWEBog2RL4qKkEbsBABPbpD4-JzMph4q8UX4FEMa0Um7t4CafFtffJNNAIl8-orsG1HUNlm4ff7vJowBhqPERLwtlD03gwqg2D0wNzRbh7mEVzqbtHfm6aARYgMFKTpLhj5pON12PE6CJMLCoLh%2BaxP1mI-b2xAGhyUgOoRH7EwPW3YUUjCHxkkfGhYksNJ8l0QhOHfEBi10AJTWXWsmE0AReA1Dl2leeYsJKXhFUoaBaQwTAREAychmLJcZjgUE9jnWghgIaBbDYWs0VogJgLYO8pk8do4AGMQ-CFKtQFoGc4CoxZTHORwJA0ao7QlIc81wUUoVQQSrFiIQ%2BwmSpCFMXETILNEkNAdNoEM0ZNzMOcvwZTxzOQJ8w1hH4aH3Gk3GA982HtNVYlUdRNBEV4SlAuBRCEGzexMTR4lIxKKSwNEPls-ZhGyAJJV%2BFF7SqKNeRTEqKjQPjWA6IguAwKToFncAv2kUJPDVKRhsq7ooH6tRcDmZA%2Br2E81UQG5sG0IbBFGjxhDfLYqtCEdXgAKxoN1sEQOB4GK9Mpvm1x1HnGhPE3RAUkwLjDiMUoAlQIRcE2MdXLIqRSxMKSvTCfCQGWh0sPgER-VMmhXKAp0aCSOxgrcqR-txQQPMENi3QgJcMFtLIjAwYteWERwOliDKWVGUEUfwZYCXa-1XUBdxQ1IUMQd8DJQD1NrsOCtgpE7X5GdBMwhjETcFBMU4IFxOZHF2XKAloMx7TYlCCDJwRcCNS7MPIVAWLlqB31iFhEEl8tEVBXY6h6zg4E-XwMFGq8dB53WpRnfIragG4wDmqoTyqslcCNqRdnePlPOlO97U4MC1Gx9onel6UzFo9hKEREp8FSQmVg0BGo7CdLNeQL5GCwT2CgkQKWHtTruvcOgAhESWfl7RkNsOY1vlwWiQmF4vo5o-Ubk50wadG6BbgiCALECr9ltWzRDqI%2BJCT5UX0D0anPAfLHDKt%2BAPu6bBpsbap8qe4%2BbEqx3vAmPdvQgboNZECFnERaUMIxQE4Grc0sdVCNjYi6S0PN4gfB9vbW0NlEDxAPJ3IY2oiAYAiqEKK6MMAv0sO9CAUYYo0DitDHUGgiCtFUlXImMgECukJlyWkS5nw4jfB%2BL8FMFCxFfpyQEegYrIFuJQEwhh2ifigRZRUjgozmQgMfJa9C%2BiCiQPHPkqASCIB1kaMs0tXYkU8NyXQPBOGWPKHdHgSx%2BJRHVu5eIRAMY4GQEQBm39aZgkON8HBHAe60i7pMNwo9qg%2BV8ACOAHwxj0HtqkW4mU6ZMAJoZB8uBKA2MFgdEWC8yS6CKvITAi0XhdGQE5EoBxzF1E8BuMScBsSCl%2BqOGsMiySUl7OPKWZp4aIE4JLG0hBHFt00LBPE9pgLBD0umSZT1tjCgPqYA0NFqhpLBMWSQ-0NFsX9oBV2jhegmHhvab27BUqWACKMPWyFHDAPyqZX41QlQQEZNU644gJijXgHAA4uRFnVCmpjABHJxyNJQSILSBx4x4XzvjaolAZIY11m0iiTBNInniA5Ni2TcnuGwH9eU-8XrlIisgCwAKrqMihLwBcwjQB0DULRRAthxAVFJOTB2bBIQ4IiOEW2dyt4nkMNMRaCVQBsHmnXbQ6ZEnrhGDTHYbtSInkVPcQQuIzhMJAJFIYmLvoSimBdLAyKwAyS8tgLq3B2JPTYMbAIuh9xAVybEBl-9PB4hrGIWJxTLF7FiAkdovAJAdASO4dMiA9UMqeoIFC092C0kRClNK2h2yYLyEveErwXX5GQZkI0rrbSnwwNAYgxkDkCEuRuIsl5vA5AxuGC6l48DIHIDhDsZo6nQQaewmFJqZ7tLrBdOWTANzpA7qwIsIgbIjB9iAIwocPhDJJlQSOwATZ92TYQRwehxDHwCGGwkf0smkB6GgfqNx9yeCtHQJ1QpPLpnneoGGtq0GNkPWc4yUNPwt28vkc5foxxFhAe7LwfIQlPEFLsTi7hEAFniLyE2kznK-Dlpa7GZayTvFJPA8Yj7epTT8oEIY18QlYVHpYGcRLXLBlLBAAAjoOgxGZbDci9BPMjqABjwFUEYzIfai4CfbOsbUvJsGsHaLyX29Dbimywn9Ay1w0SllWdikoxFCySHgZAV42och8Uae%2BUFtTsLpws-cWIuLyBgOLmAUu8qpiULEFcx2pISXA1aXybM68f4xjHCgftPJPyMOWaCTIbB0jhqYFe2sVLp36xQGMsjf17iTX6ulfiITrHBg%2BaQOALBo4vvgIZXoFi5NTHpLKkqa4FZ3x5sgEOYRompH9YpGzyBCSkAPby9geRqLaG6AEogKBEkBFTuw3Gl1-DZ2SVIuAnGwB6HTLegII3BgvkMuWDcoQMCGIfQHOAo0g6ZEsMrSGuM%2BRgHhOoZ2WwryXMArolDCAAWwFMHq7RVzEn6xwQa0QiJrjlC3sbTY%2BQZXTDSUITNWJrsJpoPd-O9I1Z4xalDsAmW21cHAKkKS-3WC9KdH6Pe-StiiK2NqfWqQgKA5WEG8io4UD8Z8A0arUldqGj6VDd81Q-oXCYOkAWtpoCmZuHMQbWkFPYCvHpWzhkWAYHzVmUyHBHCKnkv9G5BRLR6sZqQNQwUIB-DVt6HB%2BA2qUPRNxQSycVq8zCToUnDC9UjqYCysg5oinRt5AEK6eHL5FhMD8KEhZRT2akm6V6qVsLMZEKQSXCwTwHDqjeUc9nc5YBYOCSCU0vwo1ChplNe0YycjCjg3NTB%2Be-yFeQZ5ZkcvZ2MwCgyv0dh57mPgXkK2uqOeXDguW0wTBWPuggaIxAzBHahH9TLdC6T2T9yBgeNncCbm2I-crvpgItG472dSRlHBdYMgqj73xgsunolGczbySauYwPIsQNYIBxWsmoWLQwSa6BW2qwyKF7hkxDCpBMCeRdSUhsRog8xQgvRZAmxhCbhr6kijQ6pf5dL%2Bw3DYYjBDImgdCCTWgfBoYlDFj%2Bb3a4xb6CDyIv6pRdIG7wAnTvQHaNojS0j0ixw%2BAayvRbgSh8BEIp6GqjjtAQzYqGLkC1LTC1wnihqxY8w4RL7wDwQni0RCAsy6C2CGa5A-xuCWD9SjQ3DhwdyeC5BpiQDX5OJBDTwMzyCLSSjkBsQiR8LvjGaVTyg2iQCoCaAwCLTewNjEKK47Dlr2hK5075BByCiiDiADBMBdSchXRT6ORaQC4QwBrAzdCIAVZTQYy8YdDMF0j%2BzVJHR%2Brk6-DaJdR0qDQ0DrrsTrofSeQwzEQKYzzoQECYTS5mCeF1A8yTqhAf62g4h0B9ajAmCcj-ypGLQqEV6sBhoAFkZugeDwHxDRa6SSDGDBTAwsYfLuhLBuhTSt7uJLy4gMrVKeDrEYQAotbhCtTvS2D-5eFfjQR2xM6vB4APQ4KDLhzuAYDU4fGvI5K-4DAVC9gGS2gq6TAxqkZoBUDBg9h9jl63IIy4DyGTzjZUDNScC6jPRS4njl6vAN6-AMAzRQAYxI68BAA">
            100 Trinkets
        </a></td>
        <td><a href="http://400billionsuns.blogspot.com/2016/03/100-new-trinkets.html">400 Billion Suns</a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIAgzgtghgNjA04COBXKAnApiAlug9gHYgR4HogAUAjAAwDmADgJQBQoYmALiPgGYgAxhgBumACbguRbOJyDslAExM2oevhiSohSWBwwxFcehyEA1mfpTMZqgDYGLdiHEZzIAO758k-OkIoCExCLlgQACN8T1dMQX8oLgkvHC4AC3ADIxAdSQiCQgAvRWo6VRdIWBheCP05HSlElGx%2BHJA0-04qJSc1EEYoPF4BYXQxSW9fEKEUPgEYM3MwKjLnUD4dQRw%2BFGrckEwADyh6ekx0ROToRmGQdOxvdC1%2BwdDkohAYTES086EdERQZaUADMvRcAyGrS4pgi4ThECi%2BH6MBQ1m%2B6FMhHowJUa1i8QuXBwYhAGi0iHyRGKOV0OWC6QAnmAeDAdEkAlQAKxc8rAYghegXcZCfCMRh-LHWGh88DcW58fAoCj6Qx-DroLpgDqYXHg0BhOCIQTKkUAKyg4mwgK6lAALLz8YICIJfkkJnhsGATTBGFxlS0BFB%2Bv4uDBGSAbYp7LKqeZpqrshFvlbJHwDDghZhsBipChJJQY-iWdnqsmYDwIihBOYvil0m1yVbiGkgsEKDR9SQcIdkl8xRhtHSNVqwv6HqkMqlllFxBHBGzJHZ6AZUyB0wss9Gu%2BgUIRsKMRSZFlZ2v5iPau1bktI2goGecI4wYPgeMpHX1KnBIjJ-mNT60wZgIE8a0todzKmGih2nyArYsKySJpKp6UB%2BFQwgBAgShgex0oS8IpsC1AABywbwzz7J4mBwAAtIwWCcGMyRIh4rSuquWCEAA5MsGx4BGhq6g4spIRQ%2B41myCi3MGJgnB8niTncaRYNgu4RBGmCMkJNDEV2ominMfwKQ2QFxFgPCyVRHalF2ESotgXw-H8hD4HZmA8e0iT1hk%2Bmqh4cK6Ms%2BxAVkfx8N89wdgA7Hp0DfiS-gRiyTSBm0aQoNAxDhXFJRFn08QQMEEAJMSpJNqKdiAZ8%2BDCNUjCaKk8jhPIHyobKvxQCI84vlAHgYYVyTGT5jA4FaFA7NZShoesZiYIgnhpKkDkRb8FALvgvWikYyR2Ok8geAtS3rsqKxTWRgoIZI5VSisXaOZFEGEPInyzR6DZYJIYhqm%2B1DTXKqCvcgKCjeAljEOWPD1dWGTKHifSQhQrTlfs%2BlIlwwJ2l26b7pEkkePdq3gMIERwugb0ZLY9BpDwWlwNEZKYBALIyEFdIvjWp4shcjC4n9xUuQuObwZ1g2KeVyi2QUNL5FAChfDwQ1ykY8J4JIroYEz3SygTfxRHukgMuEfBsmArECIst0ifK0LKdmBIlSS2CtnhojJFuxCeFAhz-LoXxEXDFRxdUyXjtJxA6GcCyCF4%2BCZSQlrYHwBAQGSmiSM%2BlxLgUVAAJyxVUBzCyKGfEoQGUgDd74ic6mjVMIXTQFatyHsxv6Kzra1QDz3RRbKhrB6FFAl8kwi%2B07ad-NqXd9jgoEyRcGjccsC5QDElBRX9zqy-GeTRHXFx8O667J2lGU6PgIOm7s1QysW1sCIqJ31zweAfPE%2BBg9Y9Xo5b%2BLibWstsCN1ShsUColEBWnwkfRWOBSBjhwB8II3A0jMh-vsNSOBtIwXxP3Eg3BwhRntkSUWDZ0q6A%2BssaEZgIyG2qJpLBXZnbp1eEfTgPBWgZ0ZKeUY4hgRcgDhwIOFclR0lRqrfoIQ3ChG8m0F82JU7PHVnYUE1BZQI1uNALg7F5EdXQDwKeEo9CD2qjWbgGNSJrDgkKEW2g3CZVLqpFCXI7oYDOIgfAgJg6tkMZkNUFBSCYn8DI4M2EnieTHrdPS98lLLjTrgQgbIQZYEtJzCUggwiC2BBvESQj9L7CbNMX4MAGTcj%2BiyWY4U8i5mAcfWOFdvhllzBNKgFjPzGPZvGBWilgylwjPGCMZg6jQS7AoLA-McDhHKm4U4fxCz52-JMZsIAnpU30WEOkit3aRmomIVkgNLLnCImU6J7IcCoAPGKCUa0fDmE9lgX%2Bn5ckcgWPI-SG5MwqTPJqbA%2BwqynCSmOZoVAHRqMGIjAQ%2BkOhigOBgKUwI8ouCYX%2BEUizphmkwFRGA6AIxRG9orN5GYtxUCigIhReQLhy3lIrAgnBEDhSchQfYzpUHhAMSPVs6BNagivNmSQt4gJCK7s%2BFo6B1Zk0ibKcqw8Jixx0B5AqEQVhlOMb8qWB5WxR0UGdfEbJ0BnGRYNHwSyQ5AqqnZem6ZtTdH1OHUIZygX7DMLLE0xDIgXDAMsegL5kzAtJR3IQHR4wUHxRqHg5UwAjXjBjWUkCHaklfsQaQoqpwJMGOTMlKxsHwzBbcfQEBhUZoxHC06kq4nSs%2BN8CFPo-QBlzmRTYmDpHxHFH8eIdgLo2JkfcXA0B9VVVkovB5EI2Sl3LuWOhRcSEZAKS2To2lsl-ziAAqSbFXaSHMGXCS2Aoj7nhedQ4r5npbP2LTF8MROAA33EYmAHgVnU1Tp4C8pRSXJUBl6oEyxIR2vka0KsXAOTG0wfCv6bh0D4xWn8FGBgPD8y5kqZY0BTYyPRTwehGMQRW3YVhEdZhy6iTuYoHOf1dX6uuqeRWDQBzVDOCnOwwYV5UT0NwUu0pnGgqhNhxIuGU7lMkEWqwuJWkVGiZwMQLYz4uUvt494tRRoTOIBKXQ7IMZ%2BtcdgMIEouYRitCNdJp4GgNpCJWRIUEu1Gdll8A2RASyahWLpMi54kGhHCKi4gcjrBgEeAWP1RBrD%2BvRWBuw%2BLjG8dZldOJyVbOoQw-iJFLc%2BWwlZcVT%2B-QcASiHaAEjB4ARAheGYFj0llmuTrNykS0gcbq01Qa9Nu5d3ApyQXRZyLMJtCTvgawwUBQnBKy%2B6J6YypxJeSPc4QRnrD0E5h6SdjTk4wCl6nMsKBOlMm60R%2BFApUjtbp4GAwJ7P4nKtIRx8jFbq0IPuYO8pGYja0LiBFgiC6uTqPJr5XQOprlGpoGRVyPuoa0mAGgvdLG4BEIlImBBvz1wnA2PykRchhd8dkctwhu6FiE6AD6YFcbbwrQy-4NxFaHSSJj8q9LIoYz%2BiXbjrgcBWs2auZIHaRBLdQleFALIIz7D3GKEIrd-11l-XjT4UByz1I9DjTsDXvwY%2BZjjE1qVgwbC6Q3Bo9oVsjDXcD0HcgpKUDR3l8F4AhH1H5nxxb2I9S9CAA">
            100 Mundane Treasures
        </a></td>
        <td><a href="http://400billionsuns.blogspot.com/2016/02/random-tables-100-mundane-treasures.html">400 Billion Suns</a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=IIIwzgxgpmYAQCcD2SAucAUAFJAbKAtkgHYCWArgYlAA6oCGxYAlAFDADn9pmAouaigIaUOHiH1o9NsFwAzevPqYAslAAmpCPQDmSOGHqpSAN2ntcSUSYnsEZbZmD2tyosQbFzwQ3KvH1enYwAAskAGtlVAQoUQwAZXoESWVSYk1tGTBUEIJ6AFoaXEZ0DH4aMIQQUmUQ0gQGLOjdRXJ4DB9mnVb4GmQaNIBHcja2ACEkkCEEAE9MMaEphFJ4E3JcbuWWVgXcYvUSLydopBplKb36A%2BIvHdJcJdnMADVJCDSKKgIZhvvcUbuqEECDgenICHUqiQRAhrjgEBCSRKNXGpCBQjg%2BHocheQmIJBqcHo3x0gVwaXMYzRwLEyWIOjiAGE0Qg2nAAOtE8HIyjjYoQcLwpBhUJOCAMKDKZLQIiGPkwMAaOA5FaofCYRkONlTYgaLSoAFjcEHAVOBDiz6Y%2Bg0M5sRlGADk8AgxQA7pgAKrEbTLKLQqAeJBy1j2mYB3Ua61gLSUIk3EYEO1QfBPDoDWM6ZI2cRMNgYFRGZY%2BwkxCACNHKRiQ4AeEKEFZwfHVcnbRmIs4IZK4TAAGSSMSiy3UAYYjRDiOyUEecwwzzRUAAHkSdMQ2vltNkAczvWFbozoXIYjP4jMCBUZgaqEg5HItBT8GwACKkHQVluYZ%2Bvhjv4peBgAGgMf1jAIGA4AAMSQBcdEsGwnxIHQ4GGbgnHpZM4WjXUmBWNheFwYcqmmY9iRAcgy3gMhM3MXgKg0ZI%2BFo9R6Mw1xcLIxQZjoNkynY3BOINeAYKQUj-m2fh%2BklYg4AIVV8FQKwXhWMsqEUUjE1YXgbDIek4D6UgCGQRVMAAeQDNA62SZgxHuOBWHAgNyEzWJBQwAAVZY9F1S44D8ByCCoqBlLYeybAQOQoHdNzGEkKBL10pIcgDT5guKBdFSVDAezSWM2grYxYH03lWAAcSSckICcPZLUMYw1nU4q0gZEEMAALUa0gljEG87y8B8SrScI9EwBriEG-Rm2E8wRsVHTsGipdXyYANEKrOAsHmpDyCGcgoD8ckAWKvBhyWxRMAACRmJj6GyBttC8Y7o22YryHoMxMCwaNNAzF6ACtXqm2NnHoaoKo6bR3mUGaoG6XA2DO%2BhXRyJB7A1ZIJR0Nl3CQHQZiOVbGTR%2BhobZYooBMF8jHMM7w2UTKEbAAlUl1BAZO2M6OqU7j2eqSA2UMEBAmWG8qZQTRabO0XCT0CECVIOHkaMhEYFQVdSmAGAy1EuA6htJAN08IqJYQRUGBssphhWWLYySLTFTYAApYluEcA4dFdUX3qU0gxbgIQLxCZYjgAejWr2fYGSBSBodZzAAaX%2Bz2RBBUCchmG6gtYWPEVQTOSD%2B0HgBhCpTkRPY2XCPPJDYWO0ehVQWV0XHIZEd4gzjxgjgSaA5MteSGnIIMir7LSCN7f70hjuMMZuvaUVYLKIGRrRRGQNBhr4iAfgQOoAC9lBg4HLPntBuIAOWTSgQH0Vd3nCo%2BCw8o7I3wCfii6293l6lZAIZlP9LA7QL91AxzYA-UI%2BQ8h7CQJFWQOQibKGvB-e8OFWAqCXvSBB%2BBSB3yCCoe4goVTZHVAke4Mw1LSSSDUVc6lz6ECcHvTQ0oQgMDgGkDI5hT4EihIHQI8IWTYLwHPYy6YqA0FODQGc60zihSAgQMgd8irGRiN0fEJkPKMFjGsDYSQoBsCkfQGYtN7RFmUGcM4hi9G0CTjJDwqgRyIjgEuAYScKxWSQDZVgWBwRFFEIvXUchLCugxGUBEFIpC6W8eCSUejrrRhIBBQJwT1oFQCcjcwAAlJULokAyLckLQRsY%2BhGADHbVg6SgyECSDOcpYA8iBzZIgnqigUGJAZJgRIuByYIO6p-Zp2wTy%2BikuknamB6CRDgPDFmigrLYGhhoqgiIpnFDYPEVAAA6OA9thTECdHAd2DRzqcSEDGURQg-BoyKokd0ZxcAp3ku0oQZkpS0BKSsygoEQSGBMMjYiBoYh-W1sjQQ2FtiuUlMqGIoh3HdnzMmRQUB2JElwMCeRgjzCuRCOQdIGJDqQjnBGPJUdgQzFfLGV09xzmaDlqwDFp44i0oIGyLRmwUGuXWNGEy7xGVUGBVtVJrIrwgglnxOAExoywxpeCD5WgNTgmUsoSwGC2AegIAKRQSBgb6FmcUBAnlqre3ccObYrwUxUJePCwZ3SkFf2NcmGwapJQ4gwMyWAxIRCWF6Do%2Bo5hniLADLTX1hEjiNN6S2NggaCSOFnEISNVqmlhtYL62qwS2yzAZmIzycAd6kD3mQQ1MA2AAHVsQYh8CEd6ggsQQoEeSSmP9gL-3gBLOgkKi30DCFq-gJBTxskLKcSJMQATFr2KkoJzVeBpsKlQJW9RqXFppI%2Bfo%2BzSimS8LWUQ9BkLGEyKwedOKhB5Gxc1MFZFlixkgMjL66k91CsIJYU0zqYwsPJoZcwN61q-lNlJDoLY8i6U-boDVW7WK7uKeaGIsBMCn2un84wsYQ33l0buusRgqKQcJdu62ytTBFULXUQQey-jQPac0pcqlzAAA0ShhA7KBWtBhtAgFfawAAmosZQiQPC0wnaQJAGRUAzHiRAZIKSCnqSAA">
            100 Medicinal Herbs
        </a></td>
        <td><a href="http://www.drivethrurpg.com/product/184775/Medicinal-Herbs--1D100?affiliate_id=848965">dicegeeks.com</a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=FAGQpghgJgBAlgOwOYHsAuoCeYYAoAOKA7lGAE4CUwA6hAB7ACCANmALYBGcAxkwM5oyKZiiSYY3ABYQyGFgFdSzYACERKWLgCMMAG5wIzKozTSEKMsADKcZrvLxk6VYYgJuYYAFk3SN2D4cRFQMABV5ZAEwBHhUBAwARXkeAGs%2BW3syRxDVSBTyYCSZNAAvCTJMAUM%2BYABRVm5BeTZs5xV5MjA0NE8ABUlWJBbtPQMjYAAxFGFATAI%2BGFRmWGDnADlUsGZWsLc0Q2bt7zgyIUsAKWhPL2mEARQETwBhaTJuFEMYLj5uZLQa0MQhxYfiEGCshgwj2gbDgBxWGF6ZDgfDYwEe0UEcAAZvIkJ4WFJ2Mi0HMYAArFAdBCGYAAeQQmAYIDgbBwBGIpEowAAkkioLCWvC0cwIOJ7HxAsofEgENjMMEFiKJWiUBwIYcAJqbERET62Nk6fSGKjUSRwHowfCSFB8K0WeTzdkkchUR5keTcOAcVjAUKGbjlSp7Zg1KzyZg4rLelDcNIq-D4BxCx7yRPKUKbAJvRNMVmmIOBqoh4AAcSV8yNykeIswKtuPWYIrQcHuEheGBLZDc5pwRAsKRgfA6WIgHkKyVj6TsDlwzDgAEdklAqCouxLDgAJALpNzlD1en1qUcDrisPCGsau-096wQxM9SzV9CSGBY2wPtGYbukX3%2Bg6EZ1LEYdw4AxGAejoBF0AgCUBU%2BERY1LGQHgRQwRX5OEnDBVlGwVPgIRqWkOHSfk3DRVwYQecpIFRRg-B6axuCERsYBQLFwK7W42HkPZm1bT1XlYGpeVbIU1GmKA7gebwLD2LI3FgRMBB9RhOAKVd7hKIIsLpbgfmYNBB0wThhCYNUfhqaUHnSTCcgAJWtDDhgAzkqAALUQAMhTsrpZNACB8GRGARRKcM4CYMhAllXgrECzlB1sFJgF6SAyGUEthGWHSfMU61bWtd1HRcl1gB8tBZMHPYECgUqeMkaI4LE5FuNMIFFwgGAplkZFb2qz4IFMZKm0QWznCsa1dSQEQOE8Kxm0bOkkSkP9BR0qwmPlZBKvufFmBSCB6oEZK3FHSA6jnOhjlY9i5yxPozREPgUCtchSSkzwgA">
            100 Alchemical Shop Items
        </a></td>
        <td><a href="https://www.drivethrurpg.com/product/185267/Alchemical-Tools--Ingredients--1D100?affiliate_id=848965">dicegeeks.com</a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=GISwXmCeAEBGCGA7A5tAtNApgDwA4BsB7AZxADdNpl5iA6aEAM2nxABcAaaAE0M2OgAmbgA4e8ALbxkmegGMkcSsQAW8ANaZE0JN2hsVAJ0IB3bY0KHoa-M26Tps6M%2BgAoAMpsQc9TGKRDAFdcdGhiLx8YNnhDejRBfUIGRHYQeC8KLglCCh02aABGAHoAFmhESyl8aEN0pwBhHMxDAQKABkAmAmhsQs6wgEdAmMph%2BFpXAFEYgzC1TVDVDUoTTHxqgy0eQxBEdXl4QOJ%2BaAkdyyxplUGl8YAJeBArNkIUuVC1R6pjEwN6ExA1jxCIFYPhKGCUDNCMx4IDIMCrB9YkD%2BIhAJgE%2BTkgUMlAQ%2BG4iH4dCE3WgbWgAF4yS4aTTXPU1IZWJg0QJcIQvC9QrBCADemE5MY1gJ-jMVM1YMScdxAnJKDtfCwQIMQNx6NxtrtEkodGFgjiJJQcLhmvkuS9lCCAFaYOT5CxWC3iGAACgU2lg8u0SA54qs%2BCQyCGMgAlPQNtp1BUTOVfTtUNCGPl0jpAZgKFZpA9EPRXAA5SwbQzaKSGQ0B7iUDCYFMGEACXTQeGBaDuir5GT5IjhaAOkn2SDE%2BCMNjNLjN6D-QGeniPW2cxBg4gNxB6bj1ywgLSjvR9gBs1gRdHp8HFbDkKmswVC8F7mBjGsIuAEibrAlWIGwnykmhXMENsL6DQo48B%2BcggMCxK8Mc7bQLgOIUIg%2BTshuiBcLAgT5NBbIIdus5HDQlCMMYEhhChYK7oQhBqpMMSHoSMAYAYOKUI%2Bz7QK%2BKj1sk%2Bjihcmark2wJotOlDijE8bQIAGARkLycrEGiqbVAO9BurUUDQLJ3j8CGrjAEsd4ZlgrBflYGDujqpzYJgeiipeZASZBSiGNsxyNn6kraqQEiBAGIGwtkPZIDAiDpNigHrgRRy9uc17PLqKyYHsPDhQuziViaq4vtoKimCcsqXhOGoKuM9SYNEcqKOyaUYNVEHaImJg2JaEjZCkKCtrC%2BACNw7Tkk1sLHPFGzlDWOI9sQsJsCYdT%2BoQCgLvQE4WXIhCtYErx1JO7CXhspGNjQ6gxYiqwhC6E7DDo1xSNodnAvkI0zaOViwDi6RcSgYZAA">
            10 Potions
        </a></td>
        <td><a href="http://www.rolang.com/archives/333">rolang</a></td>
    </tr>
    <tr>
        <td><a href="/tools/tr/tableroller.php?t=AoGwhgngzgBAtgVygSwMYwO4AsCmA7GAewAd8cATeQwygIzCgqINUJEIQCcYpVc4cAKADquAiTKUwMcgDYYrYqW6tkeWADMwIEEQQAXZqhwxp5SIIAqXdTDX7Cp%2BGADmaGAGoAjDwyFOUoYYyDqCwJyE%2Bjio%2BpoRcDJgAF5JIGouMGkuWIb%2BMLRpeOR4OFCweVk5PKQ6UIIAIsmp6aZKOGCcYHjGngDMAIIAwjAAbrBwyGUhpZhiRKR4gv0xsAxOAEzkACyePqggCLR2LIRw9PqCALJgANYzWGzkONyMOAlUnCZQCGAjJh7rGCDAAS-Vm03m%2BEEAGUHpFYAhiDAHMisJ8THBXO4JlMQDMzBZBl0FIQ8AArLgmaQ3Qi0R48Z4jLq5bpUxIQBmcP6wLwABngagMM30c3IhBmnAQeBKnDCESiK0wyBwICe3GQGkhBA08VMeA5eDA%2Bi42kw7RFzwaOAVhloXGVlAE%2BlN2HwMGIhHsTCNMBcESllDyGG0IFgIv92RgfJgGmouU1UDYyEdDDqllwSpVarssHIyE4hh1OCpRRgJT%2BL09ePIABpnHdYC4OgI8LFMtQbnY4JjUAhwFE9ZQShgrFhJvkjVFPpQEGdPjppFg1tJWJxO2oYEuinjBwpiZNvmymzpSURNbRi9wCRAltVk88eCFO7PaPPwJlrbAIBxMNpn0jg1qIgVBwEIWjWDVfU6EZkH0Dlg1gT5-GVVsKEEAAhcBUE7KBiHvF4nxgF832kEUfVQBg2wwHAjn0PxkWQARVnZGEbg3YiVXfPE22-BAZBwDQ8RiPUOXDQgMHEbgtB0Fo8g0fMmCgBwSnKbhMTcCjdCU0lSkEAAxCIXCgNiWC6EgOW4r8f0AztCAreAEFrKD2kYJURQ4QwUDwEyMjyKA0iUdIYQcYhVh0Mt-ExXQcRQPE4lOHh9E4ZAfNRExnU4FxrRgAAKRMBGYEAOSU5AkT5fkOgiDAoAASkEIkCGNTgCCQB97EcaQlKNBATFjbhEWRDrNwDacYAgdpOFgDdvlw-AnikPBGKNZBSQw6JTnxXZyF6GBNh2a4eldAhgz%2BSg%2BuMDQ%2ByK0xC3FOU7PvTRzVwKSQxupVwsgiRFgaj8YOdAdIPIToNDg8Ed1YVlW06fRZNZJxzA5XoACIiKRPIvFRsBUAiMp6uJC98nYCTMhStkHmautNN0WMT2oybjhQJ4o35CY4sGkkCpRDiF3xoDpHUtBTX2DhKDIws0hmLx1lR6FSCYABOfknj9YtkRsd0H39Io6yiAgJjwIVmMR-GCEYUtpHYPAMjzLr4aYqBXBLShPmIa6BpRXpeVZ6Zynh698ngtRyEEABJTVvu9UssoSJ5iE%2BMomHjh6nh5H3DaicpNTUGCUFoMCwbWWbQl%2BgpCGw5wNIFXF8VLacEGMWAVWiJKhd0SdsZuWBaA5ABaLwAHo8yEcOtSYTEOWpmBOjUOsAFYAFJNe4RHH3h8AlJ4BvG6m2A%2BC6HoUSn6RowNoUeAeemw4jhZvRjdEkhaHFbs4OBYBR6ewDzJAYzyPWBQzqUKmdlnhhV0BuHUhBN5dEoFAPA4lTb5HWgVJsjAOCaEikYXqf83Rn0zgjSAVA-jvQ-jAIYpg95LiWiEfSClp6lEmM6eGAIeC-GdsiW4JglwgE1OYdSvVdSGiaqaeSnxaGfBgKHbsUpYIGkcHwp298ErwP1lidAoj2HcM1JAhIgtUDiK%2BFge0dwzZwjbOGNWmwAAcld3AaMSh0Y2hCP6dGtkIPSCl6DhQ0WGeic85AxjoV40MBCOQy0-t-NOqNXFZQwjYFowIYGaAUsbXoHh5CYxgErfiqsTCQxMIQbRdDYxcAYkxUJ18x6UAoiwT4Ro2T2MArocWRCZjBBFERRgUkcEEG1uQP2PRrz1VJBSBOThYb6kCRI5uLZnTNKXIYVuwpHBdQLE4exOAKwcj6b-bg-88EzBqa0qMMs4nNRaGXGgF84zGx2PYhRWV3pdA5AIPEVJ9DOmwg%2BFpvY2x%2BWdLQBEXTRzjm%2BDwrg6D8gRB0JPYkkNPmLIzJskI7YAhnimSYGZ%2BA5kYKvOQGCPQdqw3KcoM0OAbggtgHcHAoU0pmg6A%2BVgcA%2BoAuusGV%2BTzwrEuFBmV8bBrrjlwKqQQABpYstLgxTndBEQpu5gYck2W6AMzxJUPjyM8%2BlFpZT9DprAYIWZvmOFfM9X8Uq%2BrIlwYKfBAdSTGEpUROcnFpCQWdG0QMBA-QcFLN9ZiuFkrW12U4Y8VtjhOAORaxqjFNom0GHU61%2BRDgFAKZqI0cAoHEBeulBZe5tSwQRjtSIL1NYkB3Oa0%2BVqZjKs4Kq2UsbzTCnospFS6LHYgCCPU7g84XJMB0ZmVUD4jpVKwRUut9TmJoBMHaWgSbTA7P1f2vZ2ajnyUMGYAtWqoB1hQAAD2OHwHlaBOwwPgCqP5Ka91YBgIqzgolLWAPKPZHSm4OCcDrO0PgF6WbAmACIOY30HXGoXMO6Q1FyU5vrCYPNM8CDkHKoEqAl7e1gDpMQpSyVUrXu-CUBNhgebvgeAuuskCMgVhQKSJu27GGDUIDCMxzEyTZVlTWqMqNzX7IrWGJdcK8TEm%2BJwLQjddyfDTcQyohgnivnHOq6UhAOSkBLQUq8i0oqqR4BRCRYojK7jZmkU8haHytQGWyE21hmpTVbI4eSCGWgREoO0y9doQiGA3HhUgu4uoIYYosWENzdqmFQMmWdVUnEcjUIJNAEyMh7TSgQLw2xA1xfkH02AWxoldFiaIN0kdqkU1NMnHeK1DTRSQO4N2kBcXMC4S%2B4DLFR7ZfoTxxgzFJMyWZIkFIhQMhgAhZ0esLQLSdIfK8WOyAYLYbY3eo2HMBsuRCBycgiIKB1jtIYdghAu7OSNBhYqwRrMBoG3h6QvFwNqDtvoa6%2B83F6H0Cut92MHPQuukuY28h-LwkQcQK6TgLzddhpdGmxMHy9r5TCiNZTo2EPyhiTh09kDTvI4zKIX9MD%2BA6V4WKFZaO%2BekMQCA8pohYEWugHA263Y0BaBovwa4ZCTDKxyCb%2BsONow5nyVGtrjOEmJGAOAbsNSiQzK1Bms0Ccc0JrN663W8wzvNV7VG7H72onRODkLH3bMN2M-IFw9JVC2FJavQd9WtdXLY6VMMjhSAMGZHUcIKcZjJxtIVzwgJB1CoWoGW%2BIcACqRP-AEApn7mBO4ng2lgB6SYp57MbkyT6N63K6joUe6JGw5mUQMaUgOh47oDB%2B0q2D8NCHxKhLrJBeBhh4EzrT1K8cXR4EQBaAx6n2BHBuG5KMCLjFjaTAePAk0M6ic3ENAIQQ3u0C%2B%2Bfc1BiSJcDaBe4rtWceKnAjYNslU7hZVpq1aw%2BwTuYA24d6eMYV6YK6GwBCb6wyKxMA3AR4qyA3AhO8CAEYu5vCDdDw%2BVeKJ47Kk3rNALeXxIHwcompFprY6ol9roxNA15cpt2ci8IlkAf4P5U4kpZNxg1FTRzA1wVJN0L4v5C8Lx0hVhSxlVkc7QJ8y1v1Eh%2BFl5p4vUQ5gQEBHkb8eAIAzg2B0VBdWgLcGZTwQdroPBegn9mBc9i5dAKIlI6w4C9cLAAAZKBTyHGUqJqARVwWZVYNoDoUNfgjkOAkDYsClCA4qbFFCW0RPX0UbQ5cjJhVdLIPAWZJBJcGCarL%2BAlEwLwNQeQEnJKaQBvLuDCcw2VAbLxA%2BLhZcBNJzUNXgbQGYFbehEMULcTa0FuUPcAQ0bgEI%2BGC8OiYsAgcADAXcfeKBHDD6LSC3TsFEedbMSCO2R5CocuU0RiTIwTcuXsWUeoZIxUZFcBAgD%2BDQYsZpUqGAAARwQEsNenTxUHYC6Q5m6LrCpw2zEiYMvQ9kcGjFjEiB4CTBTDxj3xSOfQXSUQSG0Dv3sOxX4n30WGEEPSYG6KvXGkV3EhaEO3AwkMMDaNciJSjRCxgFS0-jcVYmbjmShX5WKlnDTVsESx4DuG4gRz0PZFmBWUZGwW4GlmfS4DqA6JD2OARX4jIPJxmG%2BFgmQ1LTyExFSnaiIiKHaDFjRA4EjHCVlU9QDBEGVEONeHMzpSwM7B7lJmyHjC2L7CzlJjG18n6mpLINAmtnj3MOxjbHCOiweTyQOFoi4wDw5Q1VIK90dSAyOWBjACjxgCoOkB2V7SQ03CzGAnyHoLbxiEYkDkGgbjHH2yGPs2hLUAADoYAAA1dvN%2BehD0NZKcZKGdYgA0ggY9aIyaL0gAeU1FYAxJMGOzFDwAAHIy9iwUwq4UQxRUQjQPTh8dT3x4TV5PVqocSOoWoJTYE8Jsw3SthgR6gYBeh4sw9EwCB84Bxj0ysohMQaEiQlJmIP4EN8CCiSzCEGcAEpsWlp8QktSoxNwkQBYK0DFblX9uS6Q21PBWYMDooDwIRqIwAPRYteQ0s3E6wwcC95T2QiMUlkR6JSUdlPhRi7zFwoN%2BUKE7BNRk55IAtsVf0ssPcSRSNBtuA3SVxCAfRZU0hRTEhsDShVhKFwy%2ByT8xwP1WAQLPhWAXBFpHZpdzRKRiDql2ALRYA0g7gnA7iYKWgRyxQRxYQ2T%2Bl6VPgpJdQq0FzGz%2BJj9cCngITVMDVuAKYIgGYm9SiIpDAlwOUDsZjIJXddxz9oRwSEdpApEAI0LEN%2BVxIpp9BUzYBhxnBJjdwc5Jg4dIDLDOTDspDsNGIkRSUXjMRJjCzAN3wKJDN3RwzSYKKVwjRe5CBe5QCcBe5nQQgppNRWoxZHBT8lzbTiVTBQxHAjECxiD5tuiiL%2BI%2BLbw2zTxcIyZ3QSB4oEhYZ0Z-Yby8TyBrosqIy7SmQBxxz6cek6CAw6hMtxAgLMMkEWhfjOKKgEKHJN5yTeo2FRgnotD6zkYqYudqr6k590pvj4CCViVNA3lA1YN04jYlhdUxofwv80jDENRFlKyOQhVdA8gysNxZUijVMBtkNoA-YTBgxdCSrQMKVTNbBKTpA3A2tehOLzg8z3iCYTBkpyAnhJI9xOAb1QLA0n0HhSlpBFp%2BTdo-jhcQ4YySrV5pAFr7SNw-ijknC2Q8QMh8xTwjyeDNxtBYKLR8xWkHCYYUT4DHZiEUQE5GFVyiZKJ0UtgAljr7ESk9k5qA4UQMospDBZBkYYkhAwQp0CgWhZBOKC8XAtcOlxw%2BoBAzpdQZsOgOl4TnrdwLQOQGVxKqTsx4VoVdwyyiB7JuUALWrJAnAjEihRoNjDBOhIl0UhETQtIpQoCQgDgDYx06UGVpBj0Z8ErmwaKNot5lB3bOhxC41CLlt8wmKco8hzhVMlCvl9AaoFAxxOBoqfC8AXzmkpQcAvT%2BgCxGF3BjIfbYBvgP01gPRrQIbTrwzItfRPwd9IJlAVamB2KBsxMlhFRwjHYcZFIqdKAd800lJro4iPA55hr0ryM6x9StdbA8gtTBAYyFh%2BsBciyBZOErI%2BIoDj0Ta2BmIkgaUsA8cPxE4rwqasVWxTQUQBq%2B1sxBJ6r%2BokQURSINYhlXqU8hojFHlIYxQCJz78hE7XjKog4BLda-xcDwt8RDAvArFWM-Jr1TQYaGZrw6wrYsp1RNRDzN8hViB-s6w5SfhQdOo8JkpDATCwZCg7gIqQSYUCz%2Bg3FQw6wOimRcCy6aRbBj19NuAPR6ZhTERSUytm08bTBckmHS8YA2Jwoqi1UExsZRpDslgPl7smAUQ5p0UtxyrINfUopdA8pkAwGLr1s8kugs7eLsqbgvsNwILVQ7AIhTIsovTS4qRjI75RjShYY9M0bCFkMPIF6idUV2EJGtCPQ0hYZUA0wxwERd6cwbpjQSgmGBtjBUJuAgiBdFpSN2EjltAHrQ9PRWw0oJEfRggdBYynqDDwMog8RAzPIVQU19RXQJFTwJGkyfwpGLw3RHZ%2BiioPHiRkpjJ3QsIZhTxU4lDiB-HQaXAeoygSiPQpgCgUqv4ipratRIbyDbA3TT8Bxva8Bws7SA14slSOYNUn0NwHAnT-jHkfRdGmNGLQFqb-yR9VwWokmPJOgspcxJRkxcDxbJo30n9a4ZwfczMSi9TOjDBKr3oqn25SxPtkoNB4IO0asTYPExkLFocq4YpfZQkgA">
            100 Magic Umbrellas
        </a></td>
        <td><a href="http://elfmaidsandoctopi.blogspot.com/2015/12/d100-magic-umbrellas.html">Konsumterra</a></td>
    </tr>
</table>
